[package]
name = "findrename"
version = "0.1.0"
authors = ["Louis Chan <louis@bottle.mo>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = '*'
glob = '0.3.0'
exitcode = '1.1.2'
regex = "1"
